version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: 'authdb'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: api_container
    build:
      context: .
    environment:
      PORT: 5000
      DB_NAME: authdb
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      SECRET_KEY: SECRET_KEY
    depends_on:
      - postgres
    ports:
      - '5000:5000'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
